language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm install
- npm install firebase --force
- npm test
- npm run build
deploy:
  provider: firebase
  token:
    secure: 1/TxzFeZQIVagBiWpNn8jHsBGAigSKqa41y3UmKrf5SYOP1etpKF6IOI0KEd9RSBMO
env:
  global:
    secure: Y/CEXNpOgF8wGhvdUkO36szS1Abx7tQY7jfT+DSSXwevOV7Z6gWscNDuFp9WvAIUlntp6Go4BJiqFWrNBl45qSfaEz2GYkepykS/svzHywFpHicALaiGveenSNu+cOSmKU+cas+Pm1bkyWdMLLaTX3M9gafAQOYLZb0zu+KbZQRk1h4yG50h1uLw1AJnenpe6ZiBiZmDtrIIWSJxhH9eXhNvatiWmpDxK3mJ02my7AfnDUOwrgoh9o4Qh8DEKbcUXNGgmSOh++pU1SblVsJU1E+M4MAbt0DTGWri4ag1FWK4riQp13984SLvih865hN9SGu6w9VCeKiDgVgd1RHbNxePeCBhKZp9pLzSA1xRn0JC2ynnqXEkahHhX4BxCeD0lpFNbvn4mo69pknqmeGlVenLAe41f8V2oAeOVygm5jjZNAN8LqT8oNzBKDQ1SfOiIEGd+0toKI9m+Z5ifTUEVP+2H7nf1OEToTg3szG82iVid2+FfEE4AO8pazLkbATQkig6iNdeil9K2eW/acuszd6CYP3KKHJnTyUUjjnjSEc1wGSK5wjB3Yo+izX0KFTwdeLNqnk8PdePYfVgqPiK/yI9J+vWmBTuoDWFF86Vp+Z88V12Qkljg373rE2iwi1rbw/XC8LtKqLRIh3J9flciifu/aP2N1vR0L9valZ8dgA=
